server:
  port: 8880

spring:
  application:
    name: config-client
  rabbitmq:
    host: 192.168.211.128
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      trace:
        #开启消息跟踪
        enabled: true

management:
  endpoints:
    web:
      exposure:
        #将/actuator/bus-refresh端点开放
        include: bus-refresh

eureka:
  client:
    #是否将自己注册到Eureka服务中
    register-with-eureka: true
    #是否从Eureka服务中获取注册信息
    fetch-registry: true
    #Eureka注册中心的地址,多个注册中心用,隔开
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: error
    demo.cloud: debug
