server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #git仓库地址
          uri: https://github.com/dean4lee/springcloud-demo
          #仓库地址下的路径，多个用,隔开
          search-paths: conf
          #用户名
          username:
          #密码
          password:

eureka:
  client:
    #是否将自己注册到Eureka服务中
    register-with-eureka: true
    #是否从Eureka服务中获取注册信息
    fetch-registry: false
    #Eureka注册中心的地址,多个注册中心用,隔开
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: error
    demo.cloud: debug