server:
  port: 8761

eureka:
  instance:
    #注册中心地址
    hostname: localhost
  client:
    #是否将自己注册到Eureka服务中
    register-with-eureka: false
    #是否从Eureka服务中获取注册信息
    fetch-registry: false
    #Eureka发现服务与注册服务的地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

spring:
  application:
    #服务名称
    name: eureka-server

logging:
  level:
    root: error