server:
  port: 8761

eureka:
  instance:
    #注册中心地址
    hostname: peer1
  client:
    #是否将自己注册到Eureka服务中
    register-with-eureka: true
    #是否从Eureka服务中获取注册信息
    fetch-registry: true
    #Eureka发现服务与注册服务的地址
    service-url:
      defaultZone: http://peer2:8762/eureka

spring:
  application:
    #服务名称
    name: eureka-server

logging:
  level:
    root: error